import { Track } from "@/lib/types";

export const TRACKS: Track[] = [
  {
    id: "typescript",
    title: "TypeScript",
    description: "Types, interfaces, generics, and utility types.",
    icon: "🟦",
    lessonCount: 12,
    status: "available",
  },
  {
    id: "nextjs",
    title: "Next.js",
    description:
      "File-based routing, Server Components, App Router, and deployment.",
    icon: "▲",
    lessonCount: 1,
    status: "coming-soon",
  },
  {
    id: "react",
    title: "React",
    description: "Components, hooks, state, and performance patterns.",
    icon: "⚛️",
    lessonCount: 0,
    status: "coming-soon",
  },
  {
    id: "nodejs",
    title: "Node.js",
    description: "Server-side JavaScript, APIs, streams, and modules.",
    icon: "🟢",
    lessonCount: 0,
    status: "coming-soon",
  },
  {
    id: "sql",
    title: "SQL",
    description: "Queries, joins, indexes, and database design.",
    icon: "🐘",
    lessonCount: 0,
    status: "coming-soon",
  },
  {
    id: "spring-boot",
    title: "Spring Boot",
    description: "Java microservices, REST APIs, and dependency injection.",
    icon: "☕",
    lessonCount: 0,
    status: "coming-soon",
  },
  {
    id: "kafka",
    title: "Kafka",
    description: "Event streaming, producers, consumers, and topics.",
    icon: "🟠",
    lessonCount: 0,
    status: "coming-soon",
  },
  {
    id: "docker",
    title: "Docker",
    description: "Containers, images, Compose, and deployment.",
    icon: "🐳",
    lessonCount: 0,
    status: "coming-soon",
  },
  {
    id: "aws",
    title: "AWS",
    description: "EC2, S3, Lambda, RDS, and cloud architecture.",
    icon: "☁️",
    lessonCount: 0,
    status: "coming-soon",
  },
  {
    id: "devops",
    title: "DevOps",
    description: "CI/CD pipelines, infrastructure as code, and monitoring.",
    icon: "⚙️",
    lessonCount: 0,
    status: "coming-soon",
  },
];
